### ISSUE TITLE
Mobile Browser issue if the server deployed at vds

### ISSUE THREAD

**Issue by mediaexplorer74** [PreyK/Windows-Mobile-Browser-Streaming#1]
Hi! 

I deployed the server part at VDS (Windows Core 2019). The server has real ip.
It's possible to connect to my "remote web browser" without code modification? ;)

Best,
m.e.

**Comment by PreyK** [comment]
Hi!
It should work.
The previous release had some issues when forwarding the server through ngrok but it's been fixed in the latest.
But if you have a real IP all you need is to open port 8081 for communication and you should be able to connect via `ws://yourip:8081`

**Comment by PreyK** [comment]
Feel free to reopen this issue if it doesn't work 👍
